name: Publish latest docker image

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # deploy:
  #   name: Deploy latest to homelab
  #   runs-on: ubuntu-latest
  #   needs: docker
  #   if: ${{ github.event_name != 'pull_request' }}
  #   steps:
  #     - name: Checkout GitOps Repo
  #       uses: actions/checkout@v4
  #       with:
  #         repository: lucas-dclrcq/homelabitty
  #         token: ${{ secrets.GH_PAT }}
  #         path: gitops-repo

  #     - name: Update HelmRelease File
  #       env:
  #         SHA256: ${{ needs.build.outputs.latest-sha }}
  #       run: |
  #         VERSION="latest@${SHA256}" yq eval '.spec.values.controllers.kazib.containers.main.image.tag = strenv(VERSION)' \
  #           -i gitops-repo/kubernetes/apps/downloads/kazib/app/helmrelease.yaml

  #     - name: Commit & push new version
  #       env:
  #         SHA256: ${{ needs.docker.outputs.latest-sha }}
  #       run: |
  #         cd gitops-repo
  #         git config user.name "Homelab Manager"
  #         git config user.email "homelab@manager.org"
  #         git add kubernetes/apps/downloads/kazib/app/helmrelease.yaml
  #         git commit -m "chore(kazib): update latest to ${SHA256}"
  #         git push origin main
